---
- name: Add tesseract 4 PPA
  apt_repository: repo='ppa:alex-p/tesseract-ocr'

- name: Install Leptonica
  apt:
    name: libleptonica-dev
    update_cache: yes

- name: Install Tesseract 4
  apt:
    name: tesseract-ocr
    update_cache: yes

- name: Install Tesseract Arabic
  apt:
    name: tesseract-ocr-ara
    update_cache: yes

- name: Install Tesseract French
  apt:
    name: tesseract-ocr-fra
    update_cache: yes

- name: Install Tesseract German
  apt:
    name: tesseract-ocr-deu
    update_cache: yes

- name: Install Tesseract Russian
  apt:
    name: tesseract-ocr-rus
    update_cache: yes

- name: Install Tesseract Portuguese
  apt:
    name: tesseract-ocr-por
    update_cache: yes