---
- name: Add open JDK repository on Trusty (14.04)
  apt_repository: repo='ppa:openjdk-r/ppa'
  when: ansible_os_family == "Debian" and ansible_distribution_version == "14.04"

- name: Install Java 8 JRE and JDK
  apt: name={{item}} state=latest
  with_items:
    - openjdk-8-jre-headless
    - openjdk-8-jdk
  when: ansible_os_family == "Debian"

- name: Install Java 8
  yum: name=java-1.8.0-openjdk.x86_64 state=present
  when: ansible_os_family == "RedHat"

## Workaround for Debian Java packaging bug
## See:
## https://github.com/guardian/status-app/blob/play-2.4/cloud-formation/status-app.json#L159
## https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1396760
## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775775
- name: Install Java certificates
  command: /var/lib/dpkg/info/ca-certificates-java.postinst configure
  when: ansible_os_family == "Debian"

## This modifies the JVM's DNS cache TTL, changing it from the default of INFINITY to 60
## seconds. See this issue for full details: https://github.com/guardian/amigo/issues/238
- name: Change JVM DNS cache TTL
  command: sed -i'.backup' 's/#networkaddress.cache.ttl=.*/networkaddress.cache.ttl=60/g' $(dirname $(dirname $(readlink -f $(which javac))))/jre/lib/security/java.security

