---
dependencies:
  - role: packages
    packages: 
      - git
      - binutils
      - rustc
      - cargo
      - pkg-config
      - openssl
      - libssl-dev
      - golang
      - gcc
      - g++
      - build-essential
      - gettext
      - make
      - cmake
      - wget
      - perl

