---
- name: Install packages
  apt: name=unzip state=present

- name: Download scripts
  unarchive: src="http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip" dest=/usr/local/ copy=no

