---
- name: Ensure AWS creds folder exists
  file: path=/root/.aws state=directory mode=0755

- name: Create AWS credentials file 
  template: src=credentials.template dest=/root/.aws/credentials

- name: Get Portal Tar 
  command: "aws s3 cp s3://{{artifact_bucket}}/portal/RedHat_Portal_2.0.8-devel.tar /tmp"

- name: Unpack Portal Tar
  unarchive: src=/tmp/RedHat_Portal_2.0.8-devel.tar dest=/usr/local/share copy=no

- name: Get custom Portal Install script 
  command: "aws s3 cp s3://{{artifact_bucket}}/portal/install-pluto.py /usr/local/share/RedHat_Portal_2.0.8-devel-1243" 

- name: Install deps for cantemo-python 
  yum: name=libxslt state=latest
  with_items:
    - freetype-devel.x86_64

- name: Get Portal Key 
  command: "aws s3 cp s3://{{artifact_bucket}}/portal/license.key /etc/cantemo/portal/key"

- name: Run install script
  command: python install-pluto.py chdir=/usr/local/share/RedHat_Portal_2.0.8-devel-1243

- name: Get Celery tar
  command: "aws s3 cp s3://{{artifact_bucket}}/portal/celery-3.1.16.tar.gz /tmp"

- name: Unpack Celery Tar
  unarchive: src=/tmp/celery-3.1.16.tar.gz dest=/usr/local/share copy=no

- name: Manual Celery install 
  command: /opt/cantemo/python/bin/python /usr/local/share/celery-3.1.16/setup.py install chdir=/usr/local/share/celery-3.1.16

- name: Get Pluto RPM
  command: "aws s3 cp s3://{{artifact_bucket}}/pluto/pluto-3.0-201609081627.rpm /tmp"

- name: Get NLEPlugin
  command: "aws s3 cp s3://{{artifact_bucket}}/portal/nleplugin-1.2.3-421.x86_64.rpm /tmp"

- name: Install NLEPlugin RPM
  command: yum -y --nogpgcheck localinstall nleplugin-1.2.3-421.x86_64.rpm chdir=/tmp

- name: Install Pluto RPM
  command: yum -y --nogpgcheck localinstall pluto-3.0-201609081627.rpm chdir=/tmp
