---
- name: Compile and install Nginx with the pagespeed module
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - zlib1g-dev
    - libpcre3
    - libpcre3-dev
    - unzip

- name: Create group nginx
  group: name=nginx

- name: Create user nginx
  user: name=nginx group=nginx

- name: Download and compile nginx with pagespeed module
  shell: wget https://ngxpagespeed.com/install; chmod +x install; ./install -v {{ ngxpagespeed_version }} -n {{ nginx_version }} -y -a '--sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log'

- name: Create the directory /var/log/nginx
  file: path=/var/log/nginx state=directory owner=nginx group=nginx

- name: Create the directory /etc/nginx/conf.d
  file: path=/etc/nginx/conf.d state=directory owner=nginx group=nginx

- name: Create the directory /etc/nginx/redirects
  file: path=/etc/nginx/redirects state=directory owner=nginx group=nginx

- name: Create the directory /var/cache/nginx/pagespeed
  file: path=/var/cache/nginx/pagespeed state=directory owner=nginx group=nginx

- name: Add nginx mime.types
  copy: src=mime.types dest=/etc/nginx/mime.types owner=nginx group=nginx

- name: Add nginx base config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=nginx group=nginx

- name: Add nginx logrotate config
  copy: src=logrotate.conf dest=/etc/logrotate.d/nginx

- name: Add nginx systemd service definition
  copy: src=nginx.service dest=/lib/systemd/system/nginx.service
