---
dependencies:
  - role: docker
    version: 18.06.3~ce~3-0
  - role: packages
    packages: 
      - curl
      - software-properties-common
      - zip
  - role: pip-packages 
    packages: [boto3, botocore]