---
- name: Ensure we don't swap unnecessarily
  shell: echo "vm.overcommit_memory=1" > /etc/sysctl.d/70-vm-overcommit.conf

- name: Configure locale
  command: locale-gen en_GB.UTF-8

- name: Bump ulimits
  blockinfile:
    dest: /etc/security/limits.conf
    block: |
      *  soft  nofile  16384
      *  hard  nofile  16384
      root  soft  nofile  16384
      root  hard  nofile  16384
