---
- name: Install uv with pip
  pip:
    name: "uv>={{ uv_major_version }}.{{ uv_minor_version }}.0,<{{ uv_major_version }}.{{ uv_minor_version | int + 1 }}.0"
    extra_args: "--only-binary :all:"
    executable: pip3
