- name: Download uv installer
  get_url:
    url: https://astral.sh/uv/install.sh
    dest: /tmp/uv-install.sh
- name: Install uv
  command: "sh /tmp/uv-install.sh"
  become: yes
  become_user: ubuntu
